sudo: required

language: python

stages:
  - lint
  - test-cflinuxfs2
  - test-cflinuxfs3

jobs:
  include:
    - os: linux
      dist: bionic
      stage: lint
      python: "3.6"
      install: 'pip3 install -r tests/requirements_lint.txt'
      script: make lint
    - os: linux
      dist: trusty
      stage: test-cflinuxfs2
      python: "3.4.3"
      env:
        - CF_STACK=cflinuxfs2
      install: 'pip3 install -r tests/requirements.txt'
      before_script:
        - wget --quiet "https://packages.cloudfoundry.org/stable?release=debian64&version=6.43.0&source=github-rel" -O cli.deb
        - sudo dpkg -i cli.deb
        - sudo curl -s https://download.mendix.com/Mendix-CA-G2.crt -o /usr/local/share/ca-certificates/ca.crt
        - sudo update-ca-certificates
      script:
        - make test &
        - MAKE_PID=$!
        - while [ -e /proc/$MAKE_PID ]; do echo -n "."  && sleep 60; done
        - sleep 15
        - wait $MAKE_PID
    - os: linux
      dist: bionic
      stage: test-cflinuxfs3
      python: "3.6.8"
      env:
        - CF_STACK=cflinuxfs3
      install: 'pip3 install -r tests/requirements.txt'
      before_script:
        - wget --quiet "https://packages.cloudfoundry.org/stable?release=debian64&version=6.43.0&source=github-rel" -O cli.deb
        - sudo dpkg -i cli.deb
        - sudo curl -s https://download.mendix.com/Mendix-CA-G2.crt -o /usr/local/share/ca-certificates/ca.crt
        - sudo update-ca-certificates
      script:
        - make test &
        - MAKE_PID=$!
        - while [ -e /proc/$MAKE_PID ]; do echo -n "."  && sleep 60; done
        - sleep 15
        - wait $MAKE_PID

notifications:
  email: false
